namespace Domain.WebHelpers.Models.Shared
{
    public class JsTreeData
    {

        /*{
  id          : "string" // will be autogenerated if omitted
  text        : "string" // node text
  icon        : "string" // string for custom
  state       : {
    opened    : boolean  // is the node open
    disabled  : boolean  // is the node disabled
    selected  : boolean  // is the node selected
  },
  children    : []  // array of strings or objects
  li_attr     : {}  // attributes for the generated LI node
  a_attr      : {}  // attributes for the generated A node
}*/

        /// <summary>
        /// genellikle id kolonu datası
        /// </summary>
        public string id { get; set; }

        /// <summary>
        /// görünecek text
        /// </summary>
        public string text { get; set; }

        /// <summary>
        /// node ikonu (fa fa-folder gibi)
        /// </summary>
        public string icon { get; set; }

        /// <summary>
        /// alt nodelar var mı
        /// </summary>
        public bool children { get; set; }

        public NodeState state { get; set; }

    }

    public class NodeState
    {
        public bool opened { get; set; }
        public bool disabled { get; set; }
        public bool selected { get; set; }
    }


    public class JsTreeDataList
    {

        /*{
  id          : "string" // will be autogenerated if omitted
  text        : "string" // node text
  icon        : "string" // string for custom
  state       : {
    opened    : boolean  // is the node open
    disabled  : boolean  // is the node disabled
    selected  : boolean  // is the node selected
  },
  parent    :"string"  // üst node Id
  li_attr     : {}  // attributes for the generated LI node
  a_attr      : {}  // attributes for the generated A node
}*/

        /// <summary>
        /// genellikle id kolonu datası
        /// </summary>
        public string id { get; set; }

        /// <summary>
        /// üst nodu id
        /// </summary>
        public string parent { get; set; }

        /// <summary>
        /// görünecek text
        /// </summary>
        public string text { get; set; }

        /// <summary>
        /// node ikonu (fa fa-folder gibi)
        /// </summary>
        public string icon { get; set; }

        public NodeState state { get; set; }

    }
}